### ISSUE TITLE
rest_shim.go:34: undefined: simplehttp in simplehttp.HTTPResponse

### ISSUE THREAD

**Issue by dnldd** [mailgun/mailgun-go#54]
seems the recent merge broke the build, `go get github.com/mailgun/mailgun-go` puts out the error `../../go/src/github.com/mailgun/mailgun-go/rest_shim.go:34: undefined: simplehttp in simplehttp.HTTPResponse`

**Comment by mbanzon** [comment]
Sorry - my bad merge - should've been a bit more careful.
